main_svc 1#
solarMal/java-explore-with-me pull request #2
Opened 2023-11-05 06:01 UTC by solarMal

2023-11-06 10:33 UTC, z8q requested changes

2023-11-06 10:33 UTC, z8q commented on stats-service/stats-client/src/main/java/ru/practicum/StatsClient.java
> +        String realIp = request.getRemoteAddr().equals("0:0:0:0:0:0:0:1") ? "127.0.0.1" : request.getRemoteAddr();
Это на случай, если обращение идет с localhost?

2023-11-06 10:33 UTC, z8q commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            responseDto = updateViewsAndConfirmedRequestsInEventResponseDto(event);
Тут идет обращение к сервисам и далее к базам в цикле.
Стоит чуть переделать, чтобы количество запросов к базам не зависело от количества Event-ов в iterable.
То есть стоит отправлять запросы сразу списком

2023-11-06 10:33 UTC, z8q commented on main-service/src/main/java/ru/practicum/stat/StatServiceImpl.java
> +        List<StatsResponseDto> stats = objectMapper.convertValue(response.getBody(), new TypeReference<>() {
Если придет Object в ResponseEntity, который не является `List<StatsResponseDto>` может ли тут возникнуть ошибка?

2023-11-06 16:06 UTC, solarMal commented on main-service/pom.xml
> +            <version>5.0.0</version>
без указания версии все Q-классы перестают работать и я не знаю как это починить(

2023-11-07 19:54 UTC, z8q approved these changes

2023-11-10 13:10 UTC, merged